"""Structured-reference loaders for the bug_finder.

The augmentum-dev skill maintains a set of pre-computed JSON caches
under ``.claude/skills/augmentum-dev/references/``. Each one is a
structured index of facts about the codebase that the bug_finder
agents would otherwise need to grep or model-reason about:

* **routes.json** — every HTTP endpoint (method, path, handler, file,
  line). Updated by ``refresh_refs.py``.
* **frontend_api_calls.json** — every ``fetch()`` / WebSocket call
  declared in the JS frontend. Used to identify orphaned endpoints
  (route declared, no caller).
* **settings_map.json** — every config setting and which of the four
  registration layers it appears in.
* **security_exceptions.json** — known-intentional findings the
  scanners should suppress.

This module loads them, caches them in process, and exposes typed
query helpers the agent tools wrap. Zero LLM cost; under-a-millisecond
lookups; structurally accurate because the JSON is generated by
deterministic Python scripts, not the model.

For codebases that don't ship augmentum-dev references, the loaders
return empty results — callers degrade to the framework adapter's
live AST scan.
"""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass
from pathlib import Path

# Standard reference subdirectory inside any augmentum-dev-shipping repo.
_REF_SUBPATH = (
    ".claude", "skills", "augmentum-dev", "references",
)


# ---------------------------------------------------------------------------
# Typed records
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RouteRecord:
    method: str
    path: str
    handler: str
    file: str
    line: int = 0


@dataclass(frozen=True)
class FrontendCallRecord:
    url: str
    method: str
    file: str


@dataclass(frozen=True)
class SuppressionRule:
    rule_id: str
    pattern: str            # regex or substring (interpreter-dependent)
    files: tuple[str, ...]


# ---------------------------------------------------------------------------
# Process-local cache
# ---------------------------------------------------------------------------


_CACHE_LOCK = threading.Lock()
_CACHE: dict[str, dict] = {}     # keyed by (root, filename)


def _load_json(root: Path, filename: str) -> dict:
    """Read one reference file with caching. Returns ``{}`` on
    missing-or-broken so callers can treat the absence uniformly."""
    key = f"{root.resolve()}|{filename}"
    with _CACHE_LOCK:
        cached = _CACHE.get(key)
        if cached is not None:
            return cached
    ref_path = root.joinpath(*_REF_SUBPATH, filename)
    payload: dict = {}
    if ref_path.is_file():
        try:
            data = json.loads(ref_path.read_text(encoding="utf-8"))
            if isinstance(data, dict):
                payload = data
        except (OSError, ValueError):
            payload = {}
    with _CACHE_LOCK:
        _CACHE[key] = payload
    return payload


def clear_cache() -> None:
    """Drop the in-memory cache. Useful for tests + when the user
    explicitly re-refreshes the augmentum-dev caches mid-session."""
    with _CACHE_LOCK:
        _CACHE.clear()


# ---------------------------------------------------------------------------
# routes.json
# ---------------------------------------------------------------------------


def load_routes(root: Path) -> list[RouteRecord]:
    payload = _load_json(root, "routes.json")
    out: list[RouteRecord] = []
    for r in payload.get("endpoints") or []:
        if not isinstance(r, dict):
            continue
        method = str(r.get("method") or "").upper().strip()
        path = str(r.get("path") or "").strip()
        file = str(r.get("file") or "").strip()
        if not (method and path and file):
            continue
        try:
            line = int(r.get("line") or 0)
        except (TypeError, ValueError):
            line = 0
        out.append(RouteRecord(
            method=method,
            path=path,
            handler=str(r.get("handler") or "").strip(),
            file=file,
            line=line,
        ))
    return out


def list_routes(
    root: Path,
    *,
    method: str = "",
    path_substr: str = "",
    file_substr: str = "",
    handler_substr: str = "",
    limit: int = 50,
) -> list[RouteRecord]:
    """Filtered route lookup. All filters are AND'd; empty filters
    pass everything. Substrings are case-insensitive."""
    method_norm = method.upper().strip()
    path_q = path_substr.lower().strip()
    file_q = file_substr.lower().strip()
    handler_q = handler_substr.lower().strip()
    out: list[RouteRecord] = []
    for r in load_routes(root):
        if method_norm and r.method != method_norm:
            continue
        if path_q and path_q not in r.path.lower():
            continue
        if file_q and file_q not in r.file.lower():
            continue
        if handler_q and handler_q not in r.handler.lower():
            continue
        out.append(r)
        if len(out) >= limit:
            break
    return out


# ---------------------------------------------------------------------------
# frontend_api_calls.json
# ---------------------------------------------------------------------------


def load_frontend_calls(root: Path) -> list[FrontendCallRecord]:
    payload = _load_json(root, "frontend_api_calls.json")
    out: list[FrontendCallRecord] = []
    for c in payload.get("calls") or []:
        if not isinstance(c, dict):
            continue
        url = str(c.get("url") or "").strip()
        method = str(c.get("method") or "").upper().strip()
        file = str(c.get("file") or "").strip()
        if not (url and file):
            continue
        out.append(FrontendCallRecord(url=url, method=method, file=file))
    return out


def find_callers_of(
    root: Path, *, path_substr: str, method: str = "",
) -> list[FrontendCallRecord]:
    """Frontend calls that hit endpoints matching ``path_substr``.

    Used by the lead to ask "what frontend code uses this endpoint?"
    — a route with no frontend caller is suspect (orphaned, or
    server-to-server only, or simply dead code)."""
    path_q = path_substr.lower().strip()
    method_norm = method.upper().strip()
    out: list[FrontendCallRecord] = []
    for c in load_frontend_calls(root):
        if path_q and path_q not in c.url.lower():
            continue
        if method_norm and c.method and c.method != method_norm:
            continue
        out.append(c)
    return out


# ---------------------------------------------------------------------------
# security_exceptions.json — suppression rules
# ---------------------------------------------------------------------------


def load_suppressions(root: Path) -> list[SuppressionRule]:
    payload = _load_json(root, "security_exceptions.json")
    out: list[SuppressionRule] = []
    for e in payload.get("exceptions") or []:
        if not isinstance(e, dict):
            continue
        rule_id = str(e.get("id") or "").strip()
        pattern = str(e.get("pattern") or "").strip()
        files = tuple(
            str(f).strip()
            for f in (e.get("files") or [])
            if str(f).strip()
        )
        if not rule_id or not pattern:
            continue
        out.append(SuppressionRule(
            rule_id=rule_id, pattern=pattern, files=files,
        ))
    return out


def is_finding_suppressed(
    root: Path, *, file: str, pattern: str,
) -> str:
    """Return the matching suppression rule_id, or ``""`` if none.

    Match policy:
      * ``file`` must contain (substring) one of the rule's ``files``,
      * AND the rule's ``pattern`` must contain (substring) the
        finding's ``pattern`` (or vice-versa — patterns vary in
        granularity).

    Used by scanner-result post-processing so the agent never
    re-surfaces a finding the user already triaged."""
    file_low = file.lower()
    pat_low = pattern.lower()
    for rule in load_suppressions(root):
        # File match: any rule-file substring is in the finding's path
        if rule.files and not any(
            f.lower() in file_low for f in rule.files
        ):
            continue
        if (rule.pattern.lower() in pat_low) or (pat_low in rule.pattern.lower()):
            return rule.rule_id
    return ""


# ---------------------------------------------------------------------------
# Capability check — does this workspace ship augmentum-dev refs?
# ---------------------------------------------------------------------------


def has_augmentum_dev_refs(root: Path) -> bool:
    """``True`` when the workspace ships the augmentum-dev cache
    structure. Callers use this to decide whether to consume the
    pre-built caches or run a live AST scan via the adapter."""
    ref_dir = root.joinpath(*_REF_SUBPATH)
    return ref_dir.is_dir() and any(ref_dir.glob("*.json"))
