"""Per-workspace learning substrate for the bug_finder.

Every workspace gets a ``.augmentum/bug_finder/`` directory the
bug_finder reads at the start of each audit and writes back to as
it learns. The substrate is the bug_finder's **memory of this
specific codebase** — it gets smarter every run.

Contents (one file per concern):

* ``patterns.json`` — bug patterns the bug_finder has confirmed in
  this workspace before. Future planner runs use these as priors:
  "we've seen SQL injection in store.py three times; check there
  first."
* ``suppressions.json`` — findings the user (or the lead's critique
  pass) has marked as known-intentional. Future scanner runs filter
  these out automatically. Grows over time as the bug_finder learns
  what the user considers a real bug vs. noise.
* ``custom_checks/`` — Python modules generated by the
  ``check_writer`` subagent that encode pillar-specific invariants
  unique to this codebase. Loaded by ``custom_check_runner`` on
  every subsequent run.
* ``competency.json`` — meta-info: audit count, hit rates per
  scanner, confidence calibration. Lets the system reason about
  "which scanners have been useful here".
* ``audit_history.jsonl`` — append-only trend log. One row per
  audit: counts by severity, scanner effectiveness, lead-loop stats.

This is the "positional state of competency" the user described —
the bug_finder accumulates codebase-specific knowledge that no
general-purpose tool can have. None of Snyk / CodeQL / Bandit /
Semgrep ship per-codebase learning because they're shared services.
We're local-first; our advantage is YOUR repos' history.
"""

from __future__ import annotations

import json
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from augmentum.utils.logging import get_logger

log = get_logger(__name__)


# ---------------------------------------------------------------------------
# Layout
# ---------------------------------------------------------------------------


_SUBSTRATE_REL = (".augmentum", "bug_finder")
_CUSTOM_CHECKS_REL = ("custom_checks",)


def substrate_dir(workspace_root: Path) -> Path:
    """Return the substrate directory for ``workspace_root``."""
    return workspace_root.joinpath(*_SUBSTRATE_REL)


def custom_checks_dir(workspace_root: Path) -> Path:
    """Directory containing LLM-generated AST checks."""
    return substrate_dir(workspace_root).joinpath(*_CUSTOM_CHECKS_REL)


def ensure_substrate(workspace_root: Path) -> Path:
    """Create the substrate directory tree if missing. Idempotent.

    On read-only mounts (e.g. augmentum-on-augmentum where
    ``/app/.augmentum`` is RO) mkdir of a missing subdir raises
    EROFS — that used to crash the calling tool. We now catch
    OSError and return the base path anyway; downstream writers
    have their own OSError handlers and will degrade to no-op
    instead of taking the run down.

    Returns the substrate dir for chaining."""
    base = substrate_dir(workspace_root)
    try:
        base.mkdir(parents=True, exist_ok=True)
        custom_checks_dir(workspace_root).mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        log.warning(
            "bug_finder_substrate_ensure_failed",
            workspace=str(workspace_root), error=str(exc),
        )
        return base
    gitignore = base / ".gitignore"
    if not gitignore.exists():
        # Default: workspace owners commit patterns + suppressions
        # (they're knowledge), but exclude transient logs.
        try:
            gitignore.write_text(
                "# Bug_finder workspace substrate.\n"
                "# Patterns + suppressions + custom checks are tracked.\n"
                "# Trend logs grow rapidly; ignore them by default.\n"
                "audit_history.jsonl\n"
                "competency.json\n",
                encoding="utf-8",
            )
        except OSError:
            pass
    return base


# ---------------------------------------------------------------------------
# patterns.json — learned bug patterns
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class WorkspacePattern:
    """One confirmed bug pattern from this workspace's history.

    Stable across reads; written via ``upsert_pattern``. The
    ``signature`` matches the ``ClaimSignature`` taxonomy the
    detector emits so patterns compose with the cross-run pattern
    memory in ``patterns.py``.
    """

    signature: str
    file_pattern: str         # repo-relative file or glob
    hit_count: int = 1
    fix_count: int = 0
    last_seen_at: int = 0
    sample_claim: str = ""
    severity: str = "medium"
    note: str = ""

    @property
    def is_unresolved(self) -> bool:
        """No successful fix recorded — likely still present in code."""
        return self.fix_count == 0 and self.hit_count > 0


def _patterns_path(root: Path) -> Path:
    return substrate_dir(root) / "patterns.json"


def load_workspace_patterns(root: Path) -> list[WorkspacePattern]:
    p = _patterns_path(root)
    if not p.is_file():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    out: list[WorkspacePattern] = []
    for r in data if isinstance(data, list) else []:
        if not isinstance(r, dict):
            continue
        sig = str(r.get("signature") or "").strip()
        file_pattern = str(r.get("file_pattern") or "").strip()
        if not sig or not file_pattern:
            continue
        out.append(WorkspacePattern(
            signature=sig,
            file_pattern=file_pattern,
            hit_count=int(r.get("hit_count") or 1),
            fix_count=int(r.get("fix_count") or 0),
            last_seen_at=int(r.get("last_seen_at") or 0),
            sample_claim=str(r.get("sample_claim") or ""),
            severity=str(r.get("severity") or "medium"),
            note=str(r.get("note") or ""),
        ))
    return out


def upsert_pattern(
    root: Path,
    *,
    signature: str,
    file_pattern: str,
    severity: str = "medium",
    sample_claim: str = "",
    confirmed: bool = False,
    note: str = "",
) -> WorkspacePattern:
    """Add or refresh a pattern entry. Idempotent on
    ``(signature, file_pattern)``."""
    ensure_substrate(root)
    existing = load_workspace_patterns(root)
    now = int(time.time())
    out_map: dict[tuple[str, str], WorkspacePattern] = {
        (p.signature, p.file_pattern): p for p in existing
    }
    key = (signature, file_pattern)
    current = out_map.get(key)
    if current is None:
        merged = WorkspacePattern(
            signature=signature,
            file_pattern=file_pattern,
            hit_count=1,
            fix_count=1 if confirmed else 0,
            last_seen_at=now,
            sample_claim=sample_claim,
            severity=severity,
            note=note,
        )
    else:
        merged = WorkspacePattern(
            signature=signature,
            file_pattern=file_pattern,
            hit_count=current.hit_count + 1,
            fix_count=current.fix_count + (1 if confirmed else 0),
            last_seen_at=now,
            sample_claim=sample_claim or current.sample_claim,
            severity=severity or current.severity,
            note=note or current.note,
        )
    out_map[key] = merged
    _atomic_write_json(
        _patterns_path(root),
        [_pattern_to_dict(p) for p in out_map.values()],
    )
    return merged


def _pattern_to_dict(p: WorkspacePattern) -> dict[str, Any]:
    return {
        "signature": p.signature,
        "file_pattern": p.file_pattern,
        "hit_count": p.hit_count,
        "fix_count": p.fix_count,
        "last_seen_at": p.last_seen_at,
        "sample_claim": p.sample_claim,
        "severity": p.severity,
        "note": p.note,
    }


# ---------------------------------------------------------------------------
# suppressions.json — known-intentional findings
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class WorkspaceSuppression:
    """One suppression rule. Matched against scanner findings."""

    rule_id: str
    scope: str         # "file" | "category" | "rule"
    pattern: str       # the substring to match
    reason: str = ""
    created_at: int = 0


def _suppressions_path(root: Path) -> Path:
    return substrate_dir(root) / "suppressions.json"


def load_workspace_suppressions(root: Path) -> list[WorkspaceSuppression]:
    p = _suppressions_path(root)
    if not p.is_file():
        return []
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    out: list[WorkspaceSuppression] = []
    for r in data if isinstance(data, list) else []:
        if not isinstance(r, dict):
            continue
        rule_id = str(r.get("rule_id") or "").strip()
        pattern = str(r.get("pattern") or "").strip()
        scope = str(r.get("scope") or "rule").strip().lower()
        if scope not in {"file", "category", "rule"}:
            scope = "rule"
        if not (rule_id and pattern):
            continue
        out.append(WorkspaceSuppression(
            rule_id=rule_id,
            scope=scope,
            pattern=pattern,
            reason=str(r.get("reason") or ""),
            created_at=int(r.get("created_at") or 0),
        ))
    return out


def add_suppression(
    root: Path,
    *,
    rule_id: str,
    scope: str,
    pattern: str,
    reason: str = "",
) -> None:
    """Append a suppression. Skips writes when the rule_id already
    exists (idempotent)."""
    ensure_substrate(root)
    existing = load_workspace_suppressions(root)
    if any(s.rule_id == rule_id for s in existing):
        return
    new_rule = WorkspaceSuppression(
        rule_id=rule_id,
        scope=scope,
        pattern=pattern,
        reason=reason,
        created_at=int(time.time()),
    )
    out = existing + [new_rule]
    _atomic_write_json(
        _suppressions_path(root),
        [
            {
                "rule_id": s.rule_id,
                "scope": s.scope,
                "pattern": s.pattern,
                "reason": s.reason,
                "created_at": s.created_at,
            }
            for s in out
        ],
    )


def is_suppressed(
    suppressions: list[WorkspaceSuppression],
    *,
    file: str,
    category: str,
    rule_id: str = "",
) -> str:
    """Return matching suppression rule_id or empty string.

    Match policy:
      * scope="file" → file path contains pattern
      * scope="category" → category contains pattern
      * scope="rule" → rule_id equals pattern OR category equals pattern
    """
    file_low = file.lower()
    cat_low = category.lower()
    rid_low = rule_id.lower()
    for s in suppressions:
        plow = s.pattern.lower()
        if s.scope == "file" and plow in file_low:
            return s.rule_id
        if s.scope == "category" and plow in cat_low:
            return s.rule_id
        if s.scope == "rule" and (plow == rid_low or plow == cat_low):
            return s.rule_id
    return ""


# ---------------------------------------------------------------------------
# competency.json — meta-info about this workspace's audit history
# ---------------------------------------------------------------------------


@dataclass
class Competency:
    """Aggregate state about how well the bug_finder has done on
    this workspace. Mutable; the orchestrator updates after each run."""

    audit_count: int = 0
    total_findings_ever: int = 0
    total_confirmed: int = 0
    total_fixed: int = 0
    total_false_positives: int = 0
    last_run_at: int = 0
    scanner_effectiveness: dict[str, float] = field(default_factory=dict)
    # ratio of (confirmed / produced) per scanner; higher = more
    # trustworthy. The lead weighs scanner output by this.

    def precision(self) -> float:
        if self.total_findings_ever == 0:
            return 0.0
        return self.total_confirmed / self.total_findings_ever


def _competency_path(root: Path) -> Path:
    return substrate_dir(root) / "competency.json"


def load_competency(root: Path) -> Competency:
    p = _competency_path(root)
    if not p.is_file():
        return Competency()
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return Competency()
    if not isinstance(data, dict):
        return Competency()
    se = data.get("scanner_effectiveness") or {}
    return Competency(
        audit_count=int(data.get("audit_count") or 0),
        total_findings_ever=int(data.get("total_findings_ever") or 0),
        total_confirmed=int(data.get("total_confirmed") or 0),
        total_fixed=int(data.get("total_fixed") or 0),
        total_false_positives=int(data.get("total_false_positives") or 0),
        last_run_at=int(data.get("last_run_at") or 0),
        scanner_effectiveness={
            str(k): float(v) for k, v in se.items()
        } if isinstance(se, dict) else {},
    )


def save_competency(root: Path, c: Competency) -> None:
    ensure_substrate(root)
    _atomic_write_json(_competency_path(root), {
        "audit_count": c.audit_count,
        "total_findings_ever": c.total_findings_ever,
        "total_confirmed": c.total_confirmed,
        "total_fixed": c.total_fixed,
        "total_false_positives": c.total_false_positives,
        "last_run_at": c.last_run_at,
        "scanner_effectiveness": c.scanner_effectiveness,
    })


# ---------------------------------------------------------------------------
# audit_history.jsonl — append-only trend log
# ---------------------------------------------------------------------------


def _history_path(root: Path) -> Path:
    return substrate_dir(root) / "audit_history.jsonl"


def append_audit_history(
    root: Path,
    *,
    run_id: str,
    duration_seconds: float,
    findings_by_severity: dict[str, int],
    confirmed: int = 0,
    fixed: int = 0,
    mode: str = "explore",
    tokens_used: int = 0,
    notes: list[str] | None = None,
) -> None:
    """Append one row to the trend log."""
    ensure_substrate(root)
    row = {
        "ts": int(time.time()),
        "run_id": run_id,
        "duration_seconds": round(duration_seconds, 2),
        "findings_by_severity": dict(findings_by_severity),
        "confirmed": confirmed,
        "fixed": fixed,
        "mode": mode,
        "tokens_used": tokens_used,
        "notes": notes or [],
    }
    try:
        with _history_path(root).open("a", encoding="utf-8") as fp:
            fp.write(json.dumps(row, ensure_ascii=False) + "\n")
    except OSError as exc:
        log.warning(
            "bug_finder_audit_history_append_failed",
            workspace=str(root), error=str(exc),
        )


def load_audit_history(
    root: Path, *, limit: int = 50,
) -> list[dict[str, Any]]:
    p = _history_path(root)
    if not p.is_file():
        return []
    try:
        lines = p.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    out: list[dict[str, Any]] = []
    for line in lines[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            d = json.loads(line)
            if isinstance(d, dict):
                out.append(d)
        except ValueError:
            continue
    return out


# ---------------------------------------------------------------------------
# Atomic write helper
# ---------------------------------------------------------------------------


_WRITE_LOCK = threading.Lock()


def _atomic_write_json(path: Path, payload: Any) -> None:
    """Write JSON to ``path`` atomically.

    Uses a sibling ``.tmp`` file + rename so partial writes never
    corrupt the live state. Thread-safe via a process-local lock —
    multiple bug_finder runs concurrently writing to the same
    workspace substrate would otherwise race.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with _WRITE_LOCK:
        with tmp.open("w", encoding="utf-8") as fp:
            json.dump(payload, fp, indent=2, ensure_ascii=False)
        tmp.replace(path)


# ---------------------------------------------------------------------------
# Prior-knowledge brief for the planner / lead
# ---------------------------------------------------------------------------


def unresolved_workspace_patterns(
    patterns: list[WorkspacePattern],
    *,
    min_hit_count: int = 1,
    limit: int = 20,
) -> list[WorkspacePattern]:
    """Patterns the fixer has never closed in this workspace.

    The planner consumes these as priors — "these signatures appeared
    before and were never resolved, so the code that triggered them
    is probably still buggy." Sorted by recency so the most recently
    observed unresolved patterns surface first.
    """
    candidates = [
        p for p in patterns
        if p.is_unresolved and p.hit_count >= min_hit_count
    ]
    candidates.sort(key=lambda p: p.last_seen_at, reverse=True)
    return candidates[:limit]


def familiar_workspace_patterns(
    patterns: list[WorkspacePattern],
    *,
    min_hit_count: int = 3,
    limit: int = 10,
) -> list[WorkspacePattern]:
    """Patterns this workspace has seen many times across runs.

    High recurrence count is a precision signal: when a signature has
    been flagged 3+ times and the fixer agreed at least once, the next
    surfacing is more likely to be real. Used as a planner prior to
    weight where to focus attention.
    """
    candidates = [p for p in patterns if p.hit_count >= min_hit_count]
    candidates.sort(key=lambda p: p.hit_count, reverse=True)
    return candidates[:limit]


def render_pattern_priors(
    patterns: list[WorkspacePattern],
    *,
    max_unresolved: int = 8,
    max_familiar: int = 5,
) -> str:
    """Compact "what this workspace has seen before" brief.

    Empty string when no prior knowledge exists — first-contact runs
    on a fresh workspace flow through unchanged, no prompt change.

    Layout: two short lists. **Unresolved** (likely still-present
    bugs) first because they're more actionable; **familiar** (high
    recurrence) second as a hotspot signal for where to focus.

    Surfaced to the planner + lead, NEVER the detector — the detector
    must reason from evidence in front of it, not from priors that
    could bias it toward confirming earlier findings.
    """
    if not patterns:
        return ""
    unresolved = unresolved_workspace_patterns(
        patterns, limit=max_unresolved,
    )
    familiar = familiar_workspace_patterns(patterns, limit=max_familiar)
    # Filter familiar to not overlap with unresolved — no value showing
    # the same row twice.
    unresolved_keys = {(p.signature, p.file_pattern) for p in unresolved}
    familiar = [
        p for p in familiar
        if (p.signature, p.file_pattern) not in unresolved_keys
    ]
    if not unresolved and not familiar:
        return ""
    lines: list[str] = []
    lines.append("## Prior bug patterns observed in this workspace")
    lines.append("")
    lines.append(
        "Use as a WHERE-to-look prior, not a WHAT-to-flag prior. "
        "Every finding still needs its own evidence — these are "
        "hotspot signals from past audits, not confirmed claims.",
    )
    if unresolved:
        lines.append("")
        lines.append(
            "**Unresolved** (flagged before, no successful fix recorded):",
        )
        for p in unresolved:
            sample = (p.sample_claim or "").strip()
            sample_tail = f" — {sample[:80]}" if sample else ""
            lines.append(
                f"  - `{p.signature}` in `{p.file_pattern}` "
                f"(×{p.hit_count} hits; severity {p.severity})"
                f"{sample_tail}",
            )
    if familiar:
        lines.append("")
        lines.append(
            "**Familiar** (high-recurrence, partially resolved):",
        )
        for p in familiar:
            lines.append(
                f"  - `{p.signature}` in `{p.file_pattern}` "
                f"(×{p.hit_count} hits, {p.fix_count} fixed)",
            )
    return "\n".join(lines)
