#!/usr/bin/env bash
# Auto-generated by anim_inventory.py --plan
# 72 files to delete.
# These are bytewise duplicates of files the atlas already references
# (bucket 3) or unwired duplicates where a canonical copy is kept
# (bucket 2). Review the list before running.
set -euo pipefail

# keep    ui/lib/animations/003_humidai.vrma
# keep    ui/lib/animations/006_drinkwater.vrma
# keep    ui/lib/animations/007_gekirei.vrma
# keep    ui/lib/animations/008_gatan.vrma
# keep    ui/lib/animations/airi_idle_loop.vrma
# keep    ui/lib/animations/CC0-run.vrma
# keep    ui/lib/animations/CC0-slowrun.vrma
# keep    ui/lib/animations/CC0-walk.vrma
# keep    ui/lib/animations/pose_world_connected.vrma
# keep    ui/lib/animations/pose_world_lovely.vrma
# keep    ui/lib/animations/pose_world_smiles.vrma
# keep    ui/lib/animations/pose_world_sparkle.vrma
# keep    ui/lib/animations/Reading (Loop).vrma
# keep    ui/lib/animations/Clapping.vrma
# keep    ui/lib/animations/VRMA_01.vrma
# keep    ui/lib/animations/VRMA_07.vrma
# keep    poses/external/sillytavern-pack/animation/admiration.bvh
# keep    poses/external/sillytavern-pack/animation/amusement.bvh
# keep    poses/external/sillytavern-pack/animation/annoyance.bvh
# keep    poses/external/sillytavern-pack/animation/disapproval.bvh
# keep    poses/external/sillytavern-pack/animation/excitement.bvh

git rm "poses/001_motion_pose.vrma"
git rm "poses/002_dogeza.vrma"
git rm "poses/003_humidai.vrma"
git rm "poses/004_hello_1.vrma"
git rm "poses/005_smartphone.vrma"
git rm "poses/006_drinkwater.vrma"
git rm "poses/007_gekirei.vrma"
git rm "poses/008_gatan.vrma"
git rm "poses/CC0-run.vrma"
git rm "poses/CC0-slowrun.vrma"
git rm "poses/CC0-walk.vrma"
git rm "poses/Reading (Loop).vrma"
git rm "poses/airi_idle_loop.vrma"
git rm "poses/dance_25.vrma"
git rm "poses/dance_28.vrma"
git rm "poses/dance_kebab.vrma"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/admiration.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/amusement.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/anger.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/annoyance.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/approval.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/confusion.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/curiosity.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/desire.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/disappointment.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/disapproval.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/disgust.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/embarrassment.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/excitement.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/fear.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/gratitude.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/grief.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_butt.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_chest.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_foot.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_groin.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_hands.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_head.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/hitarea_leg.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/joy.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/love.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/nervousness.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/neutral.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/optimism.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/pride.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/realization.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/relief.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/remorse.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/sadness.bvh"
git rm "poses/external/sillytavern-pack/animation_nitral-fork/surprise.bvh"
git rm "poses/external/vrm-viewer/VRMA/Angry.vrma"
git rm "poses/external/vrm-viewer/VRMA/Blush.vrma"
git rm "poses/external/vrm-viewer/VRMA/Clapping.vrma"
git rm "poses/external/vrm-viewer/VRMA/Goodbye.vrma"
git rm "poses/external/vrm-viewer/VRMA/Jump.vrma"
git rm "poses/external/vrm-viewer/VRMA/LookAround.vrma"
git rm "poses/external/vrm-viewer/VRMA/Relax.vrma"
git rm "poses/external/vrm-viewer/VRMA/Sad.vrma"
git rm "poses/external/vrm-viewer/VRMA/Sleepy.vrma"
git rm "poses/external/vrm-viewer/VRMA/Surprised.vrma"
git rm "poses/external/vrm-viewer/VRMA/Thinking.vrma"
git rm "poses/pose_world_connected.vrma"
git rm "poses/pose_world_lovely.vrma"
git rm "poses/pose_world_smiles.vrma"
git rm "poses/pose_world_sparkle.vrma"
git rm "poses/vrma/VRMA_01.vrma"
git rm "poses/vrma/VRMA_02.vrma"
git rm "poses/vrma/VRMA_03.vrma"
git rm "poses/vrma/VRMA_04.vrma"
git rm "poses/vrma/VRMA_05.vrma"
git rm "poses/vrma/VRMA_06.vrma"
git rm "poses/vrma/VRMA_07.vrma"
