"""Endpoints ingester — populates the ``endpoints`` table.

Source: ``references/routes.json`` (already auto-generated by
``refresh_refs.py`` from the live ``@router.<verb>`` decorators).
Reading from the cache rather than re-parsing keeps Phase 1 small;
the AST-based ingest can replace this later without changing the
table or query layer.

Path normalisation: FastAPI path params look like ``{task_id}`` while
the JS-call extractor emits ``{param}``. We normalise both ingesters
to ``{param}`` so the orphan JOIN works without a string distance
match.
"""

from __future__ import annotations

import json
import re
import sqlite3
from pathlib import Path

ROUTES_JSON = Path(".claude") / "skills" / "augmentum-dev" / "references" / "routes.json"
PARAM_NAME_RE = re.compile(r"\{[^/{}]+\}")


def _normalise_path(p: str) -> str:
    return PARAM_NAME_RE.sub("{param}", p)


def ingest(project_root: Path, db: sqlite3.Connection) -> None:
    src = project_root / ROUTES_JSON
    if not src.is_file():
        return
    try:
        payload = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return

    endpoints = payload.get("endpoints") or []
    if not endpoints:
        return

    # Resolve handler files to file_id once, cached to skip per-row hits.
    file_id_by_path: dict[str, int] = {
        row["path"]: int(row["id"])
        for row in db.execute("SELECT id, path FROM files")
    }

    db.execute("BEGIN")
    try:
        # endpoints rebuild fully each ingest — there's no per-row
        # source attribution beyond the JSON, and the JSON is already
        # the authoritative extract.
        db.execute("DELETE FROM endpoints")
        for entry in endpoints:
            method = (entry.get("method") or "").upper()
            raw_path = entry.get("path") or ""
            handler_file = entry.get("file") or ""
            handler_line = int(entry.get("line") or 0)
            handler_name = entry.get("handler") or ""
            if not method or not raw_path or not handler_file:
                continue
            file_id = file_id_by_path.get(handler_file)
            if file_id is None:
                # Handler in a file the files-ingester didn't visit
                # (out of SCAN_DIRS). Skip rather than insert NULL FK.
                continue
            path_template = _normalise_path(raw_path)
            db.execute(
                """INSERT OR IGNORE INTO endpoints
                   (method, path_template, handler_file_id, handler_line, handler_name)
                   VALUES (?, ?, ?, ?, ?)""",
                (method, path_template, file_id, handler_line, handler_name),
            )
        db.execute("COMMIT")
    except Exception:
        db.execute("ROLLBACK")
        raise
