"""Settings ingester — populates the ``settings`` table.

Source: ``references/settings_map.json`` (auto-generated by
``refresh_refs.py``). The extractor exposes 4 layer booleans
(config_py, config_routes, restore_map, settings_js); we map them
into the schema's 4 corresponding columns. ``in_js_defaults``,
``in_js_load``, ``in_js_sync`` were schema-defined for a future
smarter parser that distinguishes the 3 JS sub-layers — for now,
``in_js_defaults`` is populated from the single JS flag, and the
other two stay 0.

Until that smarter parser lands, queries should treat
``in_js_defaults`` as "settings.js is wired" (equivalently the
existing ``settings_js`` boolean from the JSON).
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

SETTINGS_JSON = Path(".claude") / "skills" / "augmentum-dev" / "references" / "settings_map.json"


def ingest(project_root: Path, db: sqlite3.Connection) -> None:
    src = project_root / SETTINGS_JSON
    if not src.is_file():
        return
    try:
        payload = json.loads(src.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return

    settings_list = payload.get("settings") or []
    if not settings_list:
        return

    db.execute("BEGIN")
    try:
        db.execute("DELETE FROM settings")
        for s in settings_list:
            backend_key = s.get("backend_key") or ""
            if not backend_key:
                continue
            frontend_key = s.get("frontend_key") or None
            category = s.get("category") or None
            db.execute(
                """INSERT OR IGNORE INTO settings
                   (name_snake, name_camel, type, default_value,
                    in_config_py, in_config_routes_py, in_server_restore,
                    in_js_defaults, in_js_load, in_js_sync)
                   VALUES (?, ?, ?, NULL, ?, ?, ?, ?, 0, 0)""",
                (
                    backend_key,
                    frontend_key,
                    category,
                    1 if s.get("config_py") else 0,
                    1 if s.get("config_routes") else 0,
                    1 if s.get("restore_map") else 0,
                    1 if s.get("settings_js") else 0,
                ),
            )
        db.execute("COMMIT")
    except Exception:
        db.execute("ROLLBACK")
        raise
