"""``bug_finder_run`` job handler.

Set-and-forget entry point for the bug-finder pipeline. Triggered when
the user clicks "Run Audit" inside a ``kind=bug_finder`` coder
workspace. The runner pulls the job off the queue and drives
``run_bug_finder`` to completion. Survives client disconnect; final
report is written to the ``bug_finder_runs`` table.

Payload shape (all fields validated at the top of the handler so a
malformed payload fails loudly, not silently mid-run):

    {
        "run_id":         "bfr_...",           // pre-generated by caller
        "workspace_id":   "ws_...",            // existing coder workspace
        "primary_model":  "claude-opus-4-7",   // user's selected model
        "verifier_model": "gpt-5-4",           // OPTIONAL per-workspace
                                               // override; empty = use
                                               // primary (single-model
                                               // self-verification)
        "focus_paths":    ["src/", "lib/"],    // optional
        // Optional tunables (orchestrator defaults used if absent):
        "detector_runs_per_chunk":      3,
        "detector_concurrency":         4,
        "max_chunks":                   40,
        "max_fix_attempts_per_finding": 3,
        "overall_wallclock_seconds":    1800
    }
"""

from __future__ import annotations

from dataclasses import replace as dataclass_replace
from typing import Any

from augmentum.bug_finder.knowledge_store import KnowledgeStore
from augmentum.bug_finder.orchestrator import (
    BugFinderIntake,
    BugFinderRunConfig,
    BugFinderRunReport,
    run_bug_finder,
)
from augmentum.bug_finder.patterns import PatternStore, render_pattern_brief
from augmentum.bug_finder.role_models import RoleModelConfig
from augmentum.bug_finder.store import BugFinderRunStore
from augmentum.bug_finder.task_queue import TaskQueue
from augmentum.jobs.context import JobContext
from augmentum.utils.logging import get_logger

log = get_logger(__name__)


def make_bug_finder_run_handler(app):
    """Build a handler bound to runtime app services.

    Mirrors the factory pattern used by ``make_media_sync_handler`` and
    friends: captures ``app`` at boot, returns an ``async def handler``
    that the registry calls with one ``JobContext`` per run.
    """

    async def handler(ctx: JobContext) -> dict[str, Any]:
        cm = getattr(app.state, "container_manager", None)
        if cm is None:
            raise RuntimeError(
                "bug_finder_run: container_manager not available "
                "(Docker socket missing or aiodocker not installed)",
            )
        pr = getattr(app.state, "provider_registry", None)
        if pr is None:
            raise RuntimeError(
                "bug_finder_run: provider_registry not initialized",
            )
        sm = getattr(app.state, "state_manager", None)
        sqlite_conn = (
            getattr(getattr(sm, "backend", None), "conn", None) if sm else None
        )
        if sqlite_conn is None:
            raise RuntimeError(
                "bug_finder_run: state_manager / sqlite backend not initialized",
            )

        config = _config_from_payload(ctx.payload)
        store = BugFinderRunStore(sqlite_conn)
        pattern_store = PatternStore(sqlite_conn)
        knowledge_store = KnowledgeStore(sqlite_conn)
        task_queue = TaskQueue(sqlite_conn)

        # Load prior patterns for this workspace and inject them into
        # the planner's system prompt. First run on a workspace gets an
        # empty brief — the planner system prompt is untouched.
        try:
            priors = await pattern_store.list_patterns(
                user_id=ctx.user_id,
                workspace_id=config.intake.workspace_id,
                limit=20,
            )
            brief = render_pattern_brief(priors)
            if brief:
                config = _replace_intake_with_patterns(config, brief)
        except Exception as exc:  # noqa: BLE001 — patterns are advisory
            log.warning(
                "bug_finder_pattern_load_failed",
                user_id=ctx.user_id, workspace_id=config.intake.workspace_id,
                error=str(exc),
            )

        run_id = str(ctx.payload.get("run_id") or "").strip()
        if not run_id:
            raise RuntimeError("bug_finder_run: payload missing run_id")

        # Breadcrumb row so the user has a record even if the run crashes.
        await store.start_run(
            run_id=run_id,
            user_id=ctx.user_id,
            job_id=ctx.job_id,
            git_url=None,
            workspace_id=config.intake.workspace_id,
        )

        async def _resolve_backend(model_name: str):
            return await pr.resolve_backend_with_fabric(model_name)

        await ctx.update_progress(0.02, stage="starting")

        # Event sink — push orchestrator emissions into the per-run
        # pub/sub hub the SSE route drains. Lazy-init the registry on
        # app.state so we don't depend on lifespan ordering. The sink
        # is synchronous (the orchestrator emits without awaiting)
        # because publish() itself is non-blocking — slow subscribers
        # drop on their own queue, never on the publisher.
        from augmentum.bug_finder.stream import (
            StreamEvent,
            get_or_create_hub,
        )
        registry = getattr(app.state, "bug_finder_streams", None)
        if registry is None:
            registry = {}
            app.state.bug_finder_streams = registry
        hub = get_or_create_hub(registry, run_id)

        def _event_sink(kind: str, payload: dict[str, Any], terminal: bool) -> None:
            hub.publish(StreamEvent(
                kind=kind, payload=payload, terminal=terminal,
            ))

        report: BugFinderRunReport = await run_bug_finder(
            config,
            resolve_backend=_resolve_backend,
            container_manager=cm,
            user_id=ctx.user_id,
            job_ctx=ctx,
            event_sink=_event_sink,
            knowledge_store=knowledge_store,
            task_queue=task_queue,
        )

        # The orchestrator generated its own run_id internally; reconcile
        # so the persisted row uses the caller-supplied one (the job_id
        # mapping the UI is polling on).
        if report.run_id != run_id:
            report.run_id = run_id

        # If the caller bypassed the capability gate, stamp the report
        # with the override note so downstream consumers can interpret
        # a zero-findings result in context. The flag rides through the
        # payload so this code stays at the integration boundary; the
        # orchestrator itself doesn't need to know about gating.
        if bool(ctx.payload.get("force_below_minimum")):
            from augmentum.bug_finder.capability import below_floor_note
            report.notes.append(
                below_floor_note(config.role_models.fixer),
            )

        await store.complete_run(
            report,
            user_id=ctx.user_id,
            job_id=ctx.job_id,
        )

        # Update cross-run pattern memory with whatever this run produced.
        # Same isolation as the run write: pattern memory is advisory,
        # not a transactional consumer of the run.
        try:
            await pattern_store.update_from_findings(
                report.findings,
                run_id=report.run_id,
                user_id=ctx.user_id,
                workspace_id=report.workspace_id or config.intake.workspace_id,
                seen_at=int(report.completed_at) or None,
            )
        except Exception as exc:  # noqa: BLE001
            log.warning(
                "bug_finder_pattern_update_failed",
                user_id=ctx.user_id, run_id=report.run_id, error=str(exc),
            )

        return {
            "run_id": report.run_id,
            "stop_reason": report.stop_reason,
            "findings_total": len(report.findings),
            "findings_fixed": sum(
                1 for f in report.findings if f.status == "fixed"
            ),
            "findings_confirmed": sum(
                1 for f in report.findings if f.status == "confirmed"
            ),
        }

    return handler


# ---------------------------------------------------------------------------
# Payload decoding
# ---------------------------------------------------------------------------


def _config_from_payload(payload: dict[str, Any]) -> BugFinderRunConfig:
    """Decode the job payload into a ``BugFinderRunConfig``.

    Raises ``RuntimeError`` for malformed payloads — caller (the runner)
    converts that into a failed-job row, surfacing a useful error to
    the user instead of a silent failure.
    """
    workspace_id = (payload.get("workspace_id") or "").strip()
    if not workspace_id:
        raise RuntimeError("bug_finder_run: payload missing workspace_id")

    focus_paths_raw = payload.get("focus_paths") or []
    if not isinstance(focus_paths_raw, list):
        raise RuntimeError("bug_finder_run: focus_paths must be a list of strings")
    focus_paths = tuple(str(p).strip() for p in focus_paths_raw if str(p).strip())

    primary_model = (payload.get("primary_model") or "").strip()
    if not primary_model:
        raise RuntimeError(
            "bug_finder_run: payload missing primary_model "
            "(the user's currently-selected model)",
        )
    verifier_model = (payload.get("verifier_model") or "").strip()
    # Global heavyweight slot as fallback when neither the payload nor
    # the per-workspace override is set. Lets users configure once in
    # Settings → Models → Heavyweight and have every new workspace
    # inherit a sensible verifier without per-workspace setup. The
    # per-workspace ``bug_finder_verifier_model`` (already passed via
    # ``verifier_model``) keeps overriding when set.
    if not verifier_model:
        from augmentum.config import settings as _settings
        verifier_model = (getattr(_settings, "heavyweight_model", "") or "").strip()
    try:
        role_models = RoleModelConfig.from_primary(
            primary_model, verifier=verifier_model,
        )
    except ValueError as exc:
        raise RuntimeError(f"bug_finder_run: invalid role_models — {exc}") from exc

    # Optional structured user goal. Two ergonomic shapes accepted:
    #   * full dict: {"mode": "named-bug", "description": "...", ...}
    #   * bare string: treated as ``description`` in explore mode
    # Either way, defaults to an empty explore goal so existing
    # callers behave unchanged.
    from augmentum.bug_finder.orchestrator import UserGoal
    goal_raw = payload.get("user_goal") or {}
    if isinstance(goal_raw, str):
        user_goal = UserGoal(mode="explore", description=goal_raw.strip())
    elif isinstance(goal_raw, dict):
        scope_raw = goal_raw.get("scope_paths") or ()
        scope = tuple(
            str(p).strip() for p in scope_raw if str(p).strip()
        ) if isinstance(scope_raw, list | tuple) else ()
        user_goal = UserGoal(
            mode=str(goal_raw.get("mode") or "explore").strip() or "explore",
            description=str(goal_raw.get("description") or "").strip(),
            repro_hint=str(goal_raw.get("repro_hint") or "").strip(),
            scope_paths=scope,
            severity_floor=str(goal_raw.get("severity_floor") or "info").strip() or "info",
            time_budget_minutes=int(goal_raw.get("time_budget_minutes") or 0),
        )
    else:
        user_goal = UserGoal()

    intake = BugFinderIntake(
        workspace_id=workspace_id,
        focus_paths=focus_paths,
        threat_model=str(payload.get("threat_model") or "").strip(),
        # prior_patterns is filled in later by the handler from the
        # pattern store — payload doesn't carry it because it's a
        # derived field, not user input.
        prior_patterns="",
        user_goal=user_goal,
    )

    # Tunables — fall back to defaults from BugFinderRunConfig dataclass
    # when absent. We construct with the optional fields only if the
    # payload supplied them, so dataclass defaults still apply otherwise.
    kwargs: dict[str, Any] = dict(intake=intake, role_models=role_models)
    for key in (
        "detector_runs_per_chunk",
        "detector_concurrency",
        "max_chunks",
        "max_fix_attempts_per_finding",
    ):
        if key in payload:
            kwargs[key] = int(payload[key])
    if "overall_wallclock_seconds" in payload:
        kwargs["overall_wallclock_seconds"] = float(
            payload["overall_wallclock_seconds"],
        )

    # Optional detector ensemble — list of model ids to round-robin
    # through. Filtered to non-empty strings; family classification
    # happens later in the orchestrator (no validation here).
    detector_models_raw = payload.get("detector_models") or []
    if isinstance(detector_models_raw, list):
        cleaned = tuple(
            str(m).strip() for m in detector_models_raw if str(m).strip()
        )
        if cleaned:
            kwargs["detector_models"] = cleaned

    # Opt-out toggles. Defaults-on at the dataclass level.
    if "enable_symbolic_gate" in payload:
        kwargs["enable_symbolic_gate"] = bool(payload["enable_symbolic_gate"])
    if "enable_comprehension" in payload:
        kwargs["enable_comprehension"] = bool(payload["enable_comprehension"])
    if "enable_fuzz_leg" in payload:
        kwargs["enable_fuzz_leg"] = bool(payload["enable_fuzz_leg"])

    # Pen-test leg — opt-IN (default False). When enabled, the
    # orchestrator boots the workspace's app and runs active HTTP
    # probes against confirmed findings.
    if "enable_pen_test_leg" in payload:
        kwargs["enable_pen_test_leg"] = bool(payload["enable_pen_test_leg"])
    if "pen_test_boot_command" in payload:
        kwargs["pen_test_boot_command"] = str(
            payload["pen_test_boot_command"] or "",
        )
    if "pen_test_boot_port" in payload:
        kwargs["pen_test_boot_port"] = int(payload["pen_test_boot_port"] or 0)
    if "pen_test_healthcheck_path" in payload:
        kwargs["pen_test_healthcheck_path"] = str(
            payload["pen_test_healthcheck_path"] or "/",
        )

    if "run_mode" in payload:
        kwargs["run_mode"] = str(payload["run_mode"] or "planner")

    if "detector_temperature" in payload:
        kwargs["detector_temperature"] = float(payload["detector_temperature"])
    if "detector_enable_thinking" in payload:
        kwargs["detector_enable_thinking"] = bool(
            payload["detector_enable_thinking"],
        )
    if "detector_preserve_thinking" in payload:
        kwargs["detector_preserve_thinking"] = bool(
            payload["detector_preserve_thinking"],
        )

    detector_model_override = (
        str(payload.get("detector_model") or "").strip()
    )
    if detector_model_override:
        # Frozen dataclass — replace() rather than mutate so we don't
        # carry stale shared state. Only the detector role swaps; every
        # other role keeps its primary/verifier-derived assignment.
        kwargs["role_models"] = dataclass_replace(
            role_models, detector=detector_model_override,
        )

    return BugFinderRunConfig(**kwargs)


def _replace_intake_with_patterns(
    config: BugFinderRunConfig,
    brief: str,
) -> BugFinderRunConfig:
    """Return a new config with `prior_patterns` populated on the intake.

    BugFinderIntake is frozen, so we rebuild it. Same trick as
    `dataclasses.replace`, but written long-hand to keep the import
    surface tight (the handler is hot import-path)."""
    new_intake = BugFinderIntake(
        workspace_id=config.intake.workspace_id,
        focus_paths=config.intake.focus_paths,
        threat_model=config.intake.threat_model,
        prior_patterns=brief,
        user_goal=config.intake.user_goal,
    )
    # BugFinderRunConfig is also frozen — same drill.
    return BugFinderRunConfig(
        intake=new_intake,
        role_models=config.role_models,
        planner_budget=config.planner_budget,
        detector_budget=config.detector_budget,
        verifier_budget=config.verifier_budget,
        fixer_budget=config.fixer_budget,
        detector_runs_per_chunk=config.detector_runs_per_chunk,
        detector_concurrency=config.detector_concurrency,
        max_chunks=config.max_chunks,
        max_fix_attempts_per_finding=config.max_fix_attempts_per_finding,
        overall_wallclock_seconds=config.overall_wallclock_seconds,
        detector_models=config.detector_models,
        enable_symbolic_gate=config.enable_symbolic_gate,
        enable_comprehension=config.enable_comprehension,
        enable_fuzz_leg=config.enable_fuzz_leg,
        enable_pen_test_leg=config.enable_pen_test_leg,
        pen_test_boot_command=config.pen_test_boot_command,
        pen_test_boot_port=config.pen_test_boot_port,
        pen_test_healthcheck_path=config.pen_test_healthcheck_path,
        run_mode=config.run_mode,
        detector_temperature=config.detector_temperature,
        detector_enable_thinking=config.detector_enable_thinking,
        detector_preserve_thinking=config.detector_preserve_thinking,
        fuzz_max_seconds_per_chunk=config.fuzz_max_seconds_per_chunk,
        fuzz_max_total_seconds=config.fuzz_max_total_seconds,
    )
